// index.js

Page({
  data: {
		// 测试用
		testTableConfig:[
			{
				prop:"Message",
				width:"150rpx",
				label:"first",
				needPadding:true,
			},
			{
				prop:"Name",
				width:"150rpx",
				label:"second",
				needPadding:true,
			},
			{
				prop:"Message",
				width:"150rpx",
				label:"three",
				needPadding:true,
			},
			{
				prop:"Name",
				width:"150rpx",
				label:"fourfourf",
				needPadding:true,
			},
			{
				prop:"Message",
				width:"150rpx",
				label:"five",
				needPadding:true,
			},
			{
				prop:"Message",
				width:"150rpx",
				label:"five",
				needPadding:false,
			},
		],
		// 测试用
		testTableConfigWithCheck:[
			{
				prop:"checked",
				width:"80rpx",
				label:"选择",
				needPadding:true,
			},
			{
				prop:"Message",
				width:"150rpx",
				label:"first",
				needPadding:true,
			},
			{
				prop:"Name",
				width:"150rpx",
				label:"second",
				needPadding:true,
			},
			{
				prop:"Message",
				width:"150rpx",
				label:"three",
				needPadding:true,
			},
			{
				prop:"Name",
				width:"150rpx",
				label:"fourfourf",
				needPadding:true,
			},
			{
				prop:"Message",
				width:"150rpx",
				label:"five",
				needPadding:true,
			},
			{
				prop:"Message",
				width:"150rpx",
				label:"five",
				needPadding:false,
			},
		],
		tableData:[
			{
				Name:"ccccccccccccccccccccccc",
				Message:"111111111111111111111111",
				checked:false,
				id:1,
				testArray:[
					{
					name:"11",
					label:"cc",
					},
					{
						name:"11",
						label:"cc",
					},
				]
			},
			{
				Name:"cccccccccccc",
				Message:"111111111111111111111111",
				checked:false,
				id:2,
				testArray:[{
					name:"11",
					label:"cc",
				}]
			},
			{
				Name:"cccccccccccccc",
				Message:"111111111111111111111111",
				checked:false,
				id:3,
				testArray:[{
					name:"11",
					label:"cc",
				}]
			},
			{
				Name:"cccccccccccc",
				Message:"111111111111111111111111",
				checked:false,
				id:4,
				testArray:[{
					name:"11",
					label:"cc",
				}]
			},
			{
				Name:"cccccccccccccc",
				Message:"111111111111111111111111",
				checked:false,
				id:5,
				testArray:[{
					name:"11",
					label:"cc",
				}]
			},
			{
				Name:"cccccccccccc",
				Message:"111111111111111111111111",
				checked:false,
				id:6,
				testArray:[{
					name:"11",
					label:"cc",
				}]
			},
			{
				Name:"cccccccccccccc",
				Message:"111111111111111111111111",
				checked:false,
				id:7,
				testArray:[{
					name:"11",
					label:"cc",
				}]
			},
		]
	},
	// 选择框点击事件
	checked(e){
			let {checked}= e.currentTarget.dataset;
			let index = this.data.tableData.findIndex(t=>t.id == checked.id);
			let tableData = this.data.tableData;
			if(index != -1){
				tableData[index].checked = 	!tableData[index].checked;
				this.setData({
					tableData
				})
			}
	},
	// 选择框全选--请将所有选择数据塞入要勇于勾选的数据
	changeChoice(e){
		this.setData({
			tableData:e.detail
		})
	},
	// 子组件返回点击事件数据
	rowClick(e){
		console.log(e.detail);
	}
})
